export { default as Navbar } from "./navbar/navbar";
export { default as Main } from "./main/main";
export { default as VideoDetail } from "./video-detail/video-detail";
export { default as Channels } from "./channels/channels";
export { default as Category } from "./category/category";
export { default as Videos } from "./videos/videos";
export { default as Search } from "./search/search";
export { default as Sidebar } from "./sidebar/sidebar";
export { default as VideosCard } from "./videos-card/VideosCard";
